services:
    db:
        container_name: db
        image: mariadb
        # command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: ynoserver
            MARIADB_DATABASE: ynoserver
            MARIADB_USER: ynoserver
            MARIADB_PASSWORD: ynoserver
        ports:
            - "13306:3306"
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            - NGINX_PORT=80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./sockets:/sockets
